@extends('layouts.app')

@section('content')
<style>
    /* General Page Styles */
    body {
        font-family: Arial, Helvetica, sans-serif;
        color: #000;
        background-color: #f7f7f7;
    }

    .container {
        width: 90%;
        max-width: 1000px;
        margin: 20px auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 8px;
        box-shadow: 0 2px 8px rgba(0,0,0,0.1);
    }

    h1 {
        font-size: 28px;
        margin-bottom: 5px;
        text-transform: uppercase;
        letter-spacing: 1px;
    }

    h2 {
        font-size: 16px;
        margin-bottom: 5px;
        font-weight: bold;
    }

    p {
        margin: 2px 0;
        font-size: 14px;
    }

    .header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 20px;
        border-bottom: 2px solid #ccc;
        padding-bottom: 10px;
    }

    .btn {
        padding: 8px 15px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 14px;
        margin-left: 5px;
    }

    .btn-back {
        background-color: #ccc;
        color: #000;
    }

    .btn-back:hover { background-color: #bbb; }

    .btn-print {
        background-color: #007bff;
        color: #fff;
    }

    .btn-print:hover { background-color: #0056b3; }

    /* Grid Layouts */
    .grid {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: 20px;
        margin-bottom: 20px;
    }

    .card {
        border: 1px solid #ddd;
        padding: 15px;
        border-radius: 6px;
        background-color: #f9f9f9;
    }

    /* Table Styles */
    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
    }

    th, td {
        border: 1px solid #bbb;
        padding: 8px;
        text-align: left;
        font-size: 14px;
    }

    th {
        background-color: #eee;
        font-weight: bold;
    }

    tfoot {
        font-weight: bold;
        background-color: #ddd;
    }

    /* Footer / Signature */
    .footer {
        display: flex;
        justify-content: space-between;
        margin-top: 40px;
        font-size: 13px;
    }

    .signature-line {
        margin-top: 40px;
        border-top: 1px solid #000;
        width: 150px;
    }


    .btn-mail {
    background-color: #28a745;
    color: #fff;
}
.btn-mail:hover { background-color: #218838; }

.btn-whatsapp {
    background-color: #25d366;
    color: #fff;
}
.btn-whatsapp:hover { background-color: #128c7e; }


    /* Print Styles */
    @media print {

    /* Remove everything except printable area */
    body * {
        visibility: hidden !important;
    }

    #printableArea, #printableArea * {
        visibility: visible !important;
    }

    /* Remove buttons inside printable area */
    #printableArea button,
    #printableArea .btn,
    #printableArea .btn-back,
    #printableArea .btn-print,
    #printableArea .btn-mail,
    #printableArea .btn-whatsapp {
        display: none !important;
    }

    /* Clean page look */
    #printableArea {
        position: absolute;
        left: 0;
        top: 0;
        width: 100%;
        padding: 0 !important;
        margin: 0 !important;
        box-shadow: none !important;
        border: none !important;
    }

    /* Tables fixed */
    table th {
        background: #eee !important;
        -webkit-print-color-adjust: exact !important;
    }

    @page {
        size: A4;
        margin: 12mm;
    }
}

</style>

<div class="container" id="printableArea">
    <!-- Header -->
    <div class="header">
    <div>
        <h1>Purchase Order</h1>
        <p>Generated by Marix System</p>
    </div>

    <div>
        <button class="btn btn-back" onclick="window.location='{{ route('supplier-orders.index') }}'">Back</button>
        <button class="btn btn-print" onclick="printPO()">Print</button>
        <button class="btn btn-mail" onclick="sendMail()">Mail</button>
        <button class="btn btn-whatsapp" onclick="shareWhatsApp()">WhatsApp</button>

        {{-- Return Items Button --}}
        @if(collect($supplier_order->items)->contains('type', 'sole'))
        <button onclick="window.location='{{ route('supplier-orders.return.create', $supplier_order->id) }}'"
                class="btn"
                style="background-color:#ff4d4d; color:#fff; margin-left:5px;">
            Return Items
        </button>
        @endif
    </div>
</div>


    <!-- Supplier Info -->
    <div class="grid">
        <div class="card">
            <h2>Supplier Company</h2>
            <p><strong>Business Name:</strong> {{ $supplier_order->supplier->name ?? '-' }}</p>
            <p><strong>Address:</strong> {{ $supplier_order->supplier->address ?? '-' }}</p>
            <p><strong>Email:</strong> {{ $supplier_order->supplier->email ?? '-' }}</p>
            <p><strong>Phone:</strong> {{ $supplier_order->supplier->phone ?? '-' }}</p>
            <p><strong>GST Number:</strong> {{ $supplier_order->supplier->gst_number ?? '-' }}</p>
            <p><strong>Material Types:</strong> {{ $supplier_order->supplier->material_types ?? '-' }}</p>
        </div>
        <div class="card">
            <h2>PO Summary</h2>
            <p><strong>PO Number:</strong> {{ $supplier_order->po_number }}</p>
            <p><strong>Order Date:</strong> {{ \Carbon\Carbon::parse($supplier_order->order_date)->format('d M Y') }}</p>
            <!-- <p><strong>Total Amount:</strong> ₹{{ number_format($supplier_order->total_amount, 2) }}</p> -->
        </div>
    </div>

    <!-- Items Table -->
    <table>
        <thead>
            <tr>
                <th>Type</th>
                <th>Item Name</th>
                <th>Color</th>
                <th>Quantity</th>
                <th>Unit Price (₹)</th>
                <th>Total (₹)</th>
            </tr>
        </thead>
      <tbody>
@foreach ($supplier_order->items as $item)
    @php
        $itemName = '-';
        $itemColor = '-';
        $quantityDisplay = $item['quantity'] ?? 0; // default for non-sole items

        if($item['type'] === 'raw_material') {
            $material = \App\Models\RawMaterial::find($item['id']);
            if($material) { $itemName = $material->name; $itemColor = $material->color ?? '-'; }
        } elseif($item['type'] === 'liquid_material') {
            $material = \App\Models\LiquidMaterial::find($item['id']);
            if($material) { $itemName = $material->name; $itemColor = $material->color ?? '-'; }
        } elseif($item['type'] === 'sole') {
            $material = \App\Models\Sole::find($item['id']);
            if($material) { $itemName = $material->name; $itemColor = $material->color ?? '-'; }

            // List all sizes with quantities, null => 0
            if(isset($item['sizes_qty']) && is_array($item['sizes_qty'])) {
                $sizeParts = [];
                foreach($item['sizes_qty'] as $size => $qty) {
                    $qty = $qty ?? 0; // replace null with 0
                    $sizeParts[] = "Size $size: $qty";
                }
                $quantityDisplay = implode('<br>', $sizeParts);
            }
        }

        $unitPrice = $item['price'] ?? 0;
        $totalQty = ($item['type'] === 'sole' && isset($item['sizes_qty']))
                    ? array_sum(array_map(fn($q) => $q ?? 0, $item['sizes_qty']))
                    : ($item['quantity'] ?? 0);
        $totalPrice = $totalQty * $unitPrice;
    @endphp
    <tr>
        <td>{{ ucfirst($item['type']) }}</td>
        <td>{{ $itemName }}</td>
        <td>{{ $itemColor }}</td>
        <td>{!! $quantityDisplay !!}</td>
        <td>₹{{ number_format($unitPrice, 2) }}</td>
        <td>₹{{ number_format($totalPrice, 2) }}</td>
    </tr>
@endforeach
</tbody>

        @php
    // Company GST from Settings
    $companyGst = \App\Models\Settings::get('company_gst');
    $companyState = $companyGst ? substr($companyGst, 0, 2) : null;

    // Supplier GST
    $supplierGst = $supplier_order->supplier->gst_number ?? null;
    $supplierState = $supplierGst && strlen($supplierGst) >= 2 ? substr($supplierGst, 0, 2) : null;

    // Detect GST Type
    if ($companyState === $supplierState && $companyState !== null) {
        $taxType = 'cgst'; // Intra-state
    } else {
        $taxType = 'igst'; // Inter-state
    }

    // Subtotal
    $subtotal = $supplier_order->total_amount;

    // GST Calculations
    if ($taxType === 'igst') {
        $igst = $subtotal * 0.05;   // 5%
        $cgst = 0;
        $sgst = 0;
    } else {
        $cgst = $subtotal * 0.025;  // 2.5%
        $sgst = $subtotal * 0.025;  // 2.5%
        $igst = 0;
    }

    $grandTotal = $subtotal + $cgst + $sgst + $igst;
@endphp

<tfoot>
    <tr>
        <td colspan="5" class="text-right">Subtotal</td>
        <td>₹{{ number_format($subtotal, 2) }}</td>
    </tr>

    @if($igst > 0)
        <tr>
            <td colspan="5" class="text-right">IGST (5%)</td>
            <td>₹{{ number_format($igst, 2) }}</td>
        </tr>
    @else
        <tr>
            <td colspan="5" class="text-right">CGST (2.5%)</td>
            <td>₹{{ number_format($cgst, 2) }}</td>
        </tr>
        <tr>
            <td colspan="5" class="text-right">SGST (2.5%)</td>
            <td>₹{{ number_format($sgst, 2) }}</td>
        </tr>
    @endif

    <tr>
        <td colspan="5" class="text-right" style="font-size: 16px; font-weight: bold;">Grand Total</td>
        <td style="font-size: 16px; font-weight: bold;">₹{{ number_format($grandTotal, 2) }}</td>
    </tr>
</tfoot>

    </table>

    <!-- Footer / Signature -->
    <div class="footer">
        <div>
            <p>Authorized Signature:</p>
            <div class="signature-line"></div>
        </div>
        <div>
            <p>Date: {{ \Carbon\Carbon::now()->format('d M Y') }}</p>
        </div>
    </div>
</div>

<script>
function printPO() {
    const printContents = document.getElementById('printableArea').innerHTML;

    const w = window.open('', '', 'height=900,width=1200');

    w.document.write(`
        <html>
        <head>
            <title>Purchase Order</title>

            <style>
                body { font-family: Arial, Helvetica, sans-serif; color: #000; margin: 20px; }

                table { width: 100%; border-collapse: collapse; margin-top: 20px; }
                th, td { border: 1px solid #bbb; padding: 8px; text-align: left; font-size: 12px; }
                th { background-color: #eee; font-weight: bold; -webkit-print-color-adjust: exact; }
                tfoot { font-weight: bold; background-color: #ddd; -webkit-print-color-adjust: exact; }

                .signature-line { margin-top: 40px; border-top: 1px solid #000; width: 150px; }

                /* Hide all action buttons */
                button, .btn, .btn-back, .btn-print, .btn-mail, .btn-whatsapp {
                    display: none !important;
                }

                @page { size: A4; margin: 12mm; }
            </style>
        </head>
        <body>
            ${printContents}
        </body>
        </html>
    `);

    w.document.close();
    w.focus();
    w.print();
    w.close();
}




</script>


<script>
function sendMail() {
    const subject = encodeURIComponent('Purchase Order #{{ $supplier_order->po_number }}');
    const body = encodeURIComponent(document.getElementById('printableArea').innerText);
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
}

function shareWhatsApp() {
    const message = encodeURIComponent(
        `Purchase Order #{{ $supplier_order->po_number }}\n\n` +
        document.getElementById('printableArea').innerText
    );
    // For web
    const url = `https://wa.me/?text=${message}`;
    window.open(url, '_blank');
}
</script>

@endsection
