@extends('layouts.app')

@section('content')
<style>
    body {
        font-family: Arial, Helvetica, sans-serif;
        color: #000;
        background-color: #f7f7f7;
    }

    .container {
        width: 90%;
        max-width: 1000px;
        margin: 20px auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 8px;
        box-shadow: 0 2px 8px rgba(0,0,0,0.1);
    }

    h1 {
        font-size: 28px;
        margin-bottom: 5px;
        text-transform: uppercase;
        letter-spacing: 1px;
    }

    h2 {
        font-size: 16px;
        margin-bottom: 5px;
        font-weight: bold;
    }

    p {
        margin: 2px 0;
        font-size: 14px;
    }

    .header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 20px;
        border-bottom: 2px solid #ccc;
        padding-bottom: 10px;
    }

    .btn {
        padding: 8px 15px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 14px;
        margin-left: 5px;
    }

    .btn-back {
        background-color: #ccc;
        color: #000;
    }

    .btn-back:hover { background-color: #bbb; }

    .btn-print {
        background-color: #007bff;
        color: #fff;
    }

    .btn-print:hover { background-color: #0056b3; }

    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
    }

    th, td {
        border: 1px solid #bbb;
        padding: 8px;
        text-align: left;
        font-size: 14px;
    }

    th {
        background-color: #eee;
        font-weight: bold;
    }

    .footer {
        display: flex;
        justify-content: space-between;
        margin-top: 40px;
        font-size: 13px;
    }

    .signature-line {
        margin-top: 40px;
        border-top: 1px solid #000;
        width: 150px;
    }

    @media print {
    .btn, .btn-back, .btn-print {
        display: none !important;
        visibility: hidden !important;
    }
    .header button {
        display: none !important;
        visibility: hidden !important;
    }
}

</style>

<div class="container" id="printableArea">

    {{-- Header --}}
    <div class="header">
        <div>
            <h1>Return Bill</h1>
            <p>Generated by Marix System</p>
        </div>

        <div>
            <button class="btn btn-back" onclick="window.location='{{ route('supplier-orders.returns') }}'">Back</button>
            <button class="btn btn-print" onclick="printReturn()">Print</button>
        </div>
    </div>

    {{-- Supplier Info --}}
    <div class="grid" style="display:grid;grid-template-columns:repeat(2,1fr);gap:20px;margin-bottom:20px;">
        <div class="card" style="border:1px solid #ddd;padding:15px;border-radius:6px;background-color:#f9f9f9;">
            <h2>Supplier Company</h2>
            <p><strong>Business Name:</strong> {{ $return->supplier->name }}</p>
            <p><strong>Address:</strong> {{ $return->supplier->address ?? '-' }}</p>
            <p><strong>Email:</strong> {{ $return->supplier->email ?? '-' }}</p>
            <p><strong>Phone:</strong> {{ $return->supplier->phone ?? '-' }}</p>
        </div>

        <div class="card" style="border:1px solid #ddd;padding:15px;border-radius:6px;background-color:#f9f9f9;">
            <h2>Return Details</h2>
            <p><strong>Return No:</strong> RET-{{ str_pad($return->id, 5, '0', STR_PAD_LEFT) }}</p>
            <p><strong>PO Number:</strong> {{ $return->order->po_number }}</p>
            <p><strong>Return Date:</strong> {{ $return->created_at->format('d M Y') }}</p>
            <p><strong>Status:</strong> {{ ucfirst($return->status) }}</p>
        </div>
    </div>

    {{-- Items Table --}}
    <table>
        <thead>
            <tr>
                <th>Sole</th>
                <th>Color</th>
                <th>Size</th>
                <th>Qty Returned</th>
                <th>Unit Price (₹)</th>
                <th>Total (₹)</th>
                <th>Reason</th>
            </tr>
        </thead>

        <tbody>
            @php $grandTotal = 0; @endphp

            @foreach($items as $i)
            @php
                $unitPrice = $i['price'] ?? 0;
                $totalPrice = ($i['qty'] ?? 0) * $unitPrice;
                $grandTotal += $totalPrice;
            @endphp

            <tr>
                <td>{{ $i['sole_name'] }}</td>
                <td>{{ $i['color'] }}</td>
                <td>{{ $i['size'] }}</td>
                <td>{{ $i['qty'] }}</td>
                <td>₹{{ number_format($unitPrice, 2) }}</td>
                <td>₹{{ number_format($totalPrice, 2) }}</td>
                <td>{{ $i['reason'] }}</td>
            </tr>
            @endforeach
        </tbody>

       @php
    // 🟢 Company GST (from settings)
    $companyGst = \App\Models\Settings::get('company_gst');
    $companyState = $companyGst ? substr($companyGst, 0, 2) : null;

    // 🟢 Supplier GST
    $supplierGst = $return->supplier->gst_number ?? null;
    $supplierState = $supplierGst && strlen($supplierGst) >= 2 ? substr($supplierGst, 0, 2) : null;

    // 🟢 Detect GST Type
    if ($companyState === $supplierState && $companyState !== null) {
        $taxType = 'cgst';
    } else {
        $taxType = 'igst';
    }

    // 🟢 GST Calculations
    if ($taxType === 'igst') {
        $igst = $grandTotal * 0.05;
        $cgst = 0;
        $sgst = 0;
    } else {
        $cgst = $grandTotal * 0.025;
        $sgst = $grandTotal * 0.025;
        $igst = 0;
    }

    $finalTotal = $grandTotal + $cgst + $sgst + $igst;
@endphp

<tfoot>

    <!-- Subtotal -->
    <tr style="font-weight:bold;background:#f3f3f3;">
        <td colspan="5" style="text-align:right;">Subtotal</td>
        <td colspan="2">₹{{ number_format($grandTotal, 2) }}</td>
    </tr>

    <!-- GST -->
    @if($igst > 0)
        <tr style="font-weight:bold;background:#f3f3f3;">
            <td colspan="5" style="text-align:right;">IGST (5%)</td>
            <td colspan="2">₹{{ number_format($igst, 2) }}</td>
        </tr>
    @else
        <tr style="font-weight:bold;background:#f3f3f3;">
            <td colspan="5" style="text-align:right;">CGST (2.5%)</td>
            <td colspan="2">₹{{ number_format($cgst, 2) }}</td>
        </tr>
        <tr style="font-weight:bold;background:#f3f3f3;">
            <td colspan="5" style="text-align:right;">SGST (2.5%)</td>
            <td colspan="2">₹{{ number_format($sgst, 2) }}</td>
        </tr>
    @endif

    <!-- Final Total -->
    <tr style="font-weight:bold;background:#ddd;">
        <td colspan="5" style="text-align:right;font-size:16px;">Grand Total</td>
        <td colspan="2" style="font-size:16px;">₹{{ number_format($finalTotal, 2) }}</td>
    </tr>

</tfoot>

    </table>

    {{-- Remarks --}}
    @if($return->remarks)
        <div style="margin-top:20px;">
            <p><strong>Remarks:</strong></p>
            <p style="background:#f0f0f0;padding:10px;border-radius:5px;">
                {{ $return->remarks }}
            </p>
        </div>
    @endif

    {{-- Signature --}}
    <div class="footer">
        <div>
            <p>Authorized Signature:</p>
            <div class="signature-line"></div>
        </div>
        <div>
            <p>Date: {{ now()->format('d M Y') }}</p>
        </div>
    </div>

</div>

<script>
function printReturn() {
    const printable = document.getElementById('printableArea').cloneNode(true);

    // 🔥 Remove all buttons inside the clone
    printable.querySelectorAll('button').forEach(btn => btn.remove());

    const printWindow = window.open('', '', 'height=900,width=1200');

    printWindow.document.write(`
        <html>
        <head>
            <title>Return Bill</title>
            <style>
                body { font-family: Arial, Helvetica, sans-serif; margin: 30px; }
                table { width: 100%; border-collapse: collapse; margin-top: 20px; }
                th, td { border: 1px solid #bbb; padding: 8px; text-align: left; font-size: 12px; }
                th { background-color: #eee; font-weight: bold; }
                .signature-line { margin-top: 40px; border-top: 1px solid #000; width: 150px; }
            </style>
        </head>
        <body>
            ${printable.innerHTML}
        </body>
        </html>
    `);

    printWindow.document.close();
    printWindow.focus();
    printWindow.print();
    printWindow.close();
}

</script>

@endsection
